export function Posts() {
  return (
    <>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
      <h1>Publicaciones</h1>
    </>
  );
}
